In [1]:
# Netflix user database - performing number of calculations on this set of data

import pandas as pd
import numpy as np

# Uploading and reading the dataset to check if it's loaded properly
path = '/content/Netflix Userbase.csv'

df_raw = pd.read_csv(path)


df_netflix = df_raw
df_netflix.head(5)

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
0,1,Basic,10,15-01-22,10-06-23,United States,28,Male,Smartphone,1 Month
1,2,Premium,15,05-09-21,22-06-23,Canada,35,Female,Tablet,1 Month
2,3,Standard,12,28-02-23,27-06-23,United Kingdom,42,Male,Smart TV,1 Month
3,4,Standard,12,10-07-22,26-06-23,Australia,51,Female,Laptop,1 Month
4,5,Basic,10,01-05-23,28-06-23,Germany,33,Male,Smartphone,1 Month

In [ ]:
# Evaluating the dataset to determine if there are any null values + checking on data types available
df_netflix.info()
df_netflix.describe().T
df_netflix.notnull().values.any()

In [ ]:
# Let's see where the most users come from with Premium subscription

premium = df_netflix['Subscription Type'] == "Premium"
top_premium_by_country = df_netflix[premium]
top_premium_by_country['Country'].value_counts().nlargest(5)

In [ ]:
# Checking what is the top 3 youngest nation user wise
average_age = df_netflix.groupby('Country')['Age'].mean().sort_values(ascending=True).nlargest(3)
print(average_age)

In [ ]:
# What is the most frequently used device among users >50 years old?
df_netflix['Age'] = df_netflix['Age'].astype(int)
elderly = df_netflix[df_netflix['Age'] > 50]

elderly['Device'].value_counts()

In [ ]:

# Let's distinguish that by gender
elderly.groupby('Gender')['Device'].value_counts()

In [2]:
# Let's see what is the central date in the column Join Date and see whether more users joined before or after the middle date
df_netflix["Join Date"] = pd.to_datetime(df_netflix["Join Date"])

maxx = df_netflix["Join Date"].max()
minn = df_netflix["Join Date"].min()

differential = (maxx - minn) / 2
meet_me_halfway = minn + differential
print(differential)
print(meet_me_halfway)

before_mid = df_netflix[df_netflix['Join Date'] < meet_me_halfway]
after_or_on_mid = df_netflix[df_netflix['Join Date'] >= meet_me_halfway].value_counts()

print(len(before_mid))
print(len(after_or_on_mid))

468 days 00:00:00
2022-08-20 00:00:00
1413
1087